### ISSUE TITLE
contributing data

### ISSUE THREAD

**Issue by rootsmusic** [DLu/Pennsylvania2020#1]
You may be interested in coding [parsers](https://github.com/openelections/openelections-data-pa/tree/master/parsers) and [supporting code](http://docs.openelections.net/guide/preprocessing/) to scrape [crowdsourced precinct-level election results](http://docs.openelections.net/getting-involved/) for OpenElections.

**Comment by rootsmusic** [comment]
Post edited to change link for "[supporting code](http://docs.openelections.net/guide/preprocessing/)".

**Comment by DLu** [comment]
Thanks for pointing me at this project. How active is it these days? 

I see @dwillis is doing some work in PA [here](https://github.com/openelections/openelections-sources-pa/issues/12)

Unfortunately it seems like the data source I was using for county-by-county vote totals is ephemeral, meaning the link I was using for [2020](https://electionreturns.pa.gov/electionFeed.aspx?ID=31) is no longer valid. So I'm going to need a little more guidance on how to jump in.

**Comment by rootsmusic** [comment]
It's active, but each state's level of activeness depends on the number of contributors.  There are many ways to contribute, and some ways don't need uploading new files.  You can ask how to help in https://github.com/openelections/openelections-data-pa/pull/71

**Comment by rootsmusic** [comment]
It's active, but each state's level of activeness depends on the number of contributors.  There are many ways to contribute, and some ways don't need uploading new files.  You can ask how to help in https://github.com/openelections/openelections-data-pa/pull/71
